@startuml
'https://plantuml.com/class-diagram'

abstract class Metadata
{
    - Name: String
    - Description: String
    - Action: Action
}

entity Page
{

}

entity Section
{
    - Page: Page
}

entity Item
{
    - Content: Content
    - Section: Section
    - Type: ItemType
}

enum ItemType
{
    LIST
    TEXT
    IMAGE
    VIDEO
}

entity Content <<(V, #229988)>>
{
    - Text: String
    - Image: Buffer
}

entity Comment
{
    - String: Text
    - Page: Page
    - Action: Action
}

entity Account
{
    - FullName: String
    - Username: String
    - Password: String
    - Action: Action
    - AccountType: AccountType
}

enum AccountType
{
    USER
    EDITOR
    ADMINISTRATOR
    OWNER
}

entity Action <<(V, #229988)>>
{
    - Date: LocalDateTime
    - Type: ActionType
}

enum ActionType
{
    CREATE
    EDIT
    DELETE
}

Account .up. AccountType

Action -left-* Metadata
Action -right-> Account
Action -down-* Comment
Action .up. ActionType

Comment -left-* Page

Page -up-|> Metadata

Section -up-|> Metadata
Section -right-* Page

Item -right-|> Metadata
Item -down-* Section
Item -left-> Content
Item .up. ItemType


@enduml