@startuml
'https://plantuml.com/class-diagram'

abstract class Metadata <<Parent>>
{
    - Name: String
    - Description: String
    - Change: Change
}

entity Page
{
    - Sections: Set<Section>
    - Comments: Set<Comment>
}

entity Section
{
    - Items: Set<Item>
}

entity Item
{
    - Type: ItemType
    - Content: Content
}

enum ItemType
{
    PARAGRAPH
    LIST
    IMAGE
    VIDEO
}

entity Content <<(V, #229988)Embeddable>>
{
    - Text: String
    - Image: Buffer
}

entity Comment
{
    - String: Text
}

entity Account
{
    - FullName: String
    - Username: String
    - Password: String
    - Change: Change
    - AccountType: AccountType
}

enum AccountType
{
    USER
    EDITOR
    ADMIN
    OWNER
}

entity Change <<(V, #229988)Embeddable>>
{
    - Date: String
    - Type: ChangeType
}

enum ChangeType
{
    CREATE
    EDIT
    DELETE
}

Page -up-|> Metadata

Section -up-|> Metadata
Section -right-* Page

Item -right-|> Metadata
Item -down-* Section
Item -right-> Content
Item .up. ItemType

Content -right-|> Metadata

Comment -up-* Change
Comment -left-* Page

Change -left-* Metadata
Change -right-> Account
Change .up. ChangeType

Account .up. AccountType

@enduml